[package]
name = "hhkb2020-rs"
version = "0.1.0"
authors = ["hiratasa <36002166+hiratasa@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "hhkb2020-a"
path = "src/a.rs"

[[bin]]
name = "hhkb2020-b"
path = "src/b.rs"

[[bin]]
name = "hhkb2020-c"
path = "src/c.rs"

[[bin]]
name = "hhkb2020-d"
path = "src/d.rs"

[[bin]]
name = "hhkb2020-e"
path = "src/e.rs"

[[bin]]
name = "hhkb2020-f"
path = "src/f.rs"
