[package]
name = "dwacon5th_prelims-rs"
version = "0.1.0"
authors = ["hiratasa <36002166+hiratasa@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.2.1"
rustc-hash = "1.1.0"

[[bin]]
name = "dwacon5th_prelims-a"
path = "src/a.rs"

[[bin]]
name = "dwacon5th_prelims-b"
path = "src/b.rs"

[[bin]]
name = "dwacon5th_prelims-c"
path = "src/c.rs"

[[bin]]
name = "dwacon5th_prelims-d"
path = "src/d.rs"

[[bin]]
name = "dwacon5th_prelims-e"
path = "src/e.rs"

[[bin]]
name = "dwacon5th_prelims-f"
path = "src/f.rs"
