[package]
name = "dp-rs"
version = "0.1.0"
authors = ["hiratasa <36002166+hiratasa@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.2.1"
rustc-hash = "1.1.0"
bitset-fixed = "0.1.0"
itertools = "0.9.0"
ordered-float = "1.0.2"
itertools-num = "0.1.3"
rand = { version = "0.7.3", features = ["small_rng"] }
permutohedron = "0.2.4"
proconio = "0.3.6"

[[bin]]
name = "dp-a"
path = "src/a.rs"

[[bin]]
name = "dp-b"
path = "src/b.rs"

[[bin]]
name = "dp-c"
path = "src/c.rs"

[[bin]]
name = "dp-d"
path = "src/d.rs"

[[bin]]
name = "dp-h"
path = "src/h.rs"

[[bin]]
name = "dp-j"
path = "src/j.rs"

[[bin]]
name = "dp-k"
path = "src/k.rs"

[[bin]]
name = "dp-l"
path = "src/l.rs"

[[bin]]
name = "dp-m"
path = "src/m.rs"

[[bin]]
name = "dp-n"
path = "src/n.rs"

[[bin]]
name = "dp-o"
path = "src/o.rs"

[[bin]]
name = "dp-p"
path = "src/p.rs"

[[bin]]
name = "dp-q"
path = "src/q.rs"

[[bin]]
name = "dp-r"
path = "src/r.rs"

[[bin]]
name = "dp-s"
path = "src/s.rs"

[[bin]]
name = "dp-t"
path = "src/t.rs"

[[bin]]
name = "dp-u"
path = "src/u.rs"

[[bin]]
name = "dp-uy"
path = "src/uy.rs"

[[bin]]
name = "dp-v"
path = "src/v.rs"

[[bin]]
name = "dp-w"
path = "src/w.rs"

[[bin]]
name = "dp-x"
path = "src/x.rs"

[[bin]]
name = "dp-y"
path = "src/y.rs"

[[bin]]
name = "dp-z"
path = "src/z.rs"
