[package]
name = "library_chcker-rs"
version = "0.1.0"
authors = ["hiratasa <36002166+hiratasa@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "library_chcker-a"
path = "src/a.rs"

[[bin]]
name = "library_chcker-b"
path = "src/b.rs"

[[bin]]
name = "library_chcker-c"
path = "src/c.rs"

[[bin]]
name = "library_chcker-d"
path = "src/d.rs"

[[bin]]
name = "library_chcker-e"
path = "src/e.rs"

[[bin]]
name = "library_chcker-f"
path = "src/f.rs"

[[bin]]
name = "library_chcker-point_add_range_sum"
path = "src/point_add_range_sum.rs"

[[bin]]
name = "library_chcker-point_set_range_composite"
path = "src/point_set_range_composite.rs"

[[bin]]
name = "library_chcker-range_affine_range_sum"
path = "src/range_affine_range_sum.rs"

[[bin]]
name = "library_chcker-dynamic_sequence_range_affine_range_sum"
path = "src/dynamic_sequence_range_affine_range_sum.rs"
