[package]
name = "typical90-rs"
version = "0.1.0"
authors = ["hiratasa <36002166+hiratasa@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.2.1"
rustc-hash = "1.1.0"
bitset-fixed = "0.1.0"
itertools = "0.9.0"
ordered-float = "1.0.2"
itertools-num = "0.1.3"
rand = { version = "0.7.3", features = ["small_rng"] }
permutohedron = "0.2.4"
proconio = "0.3.6"

[[bin]]
name = "typical90-a"
path = "src/a.rs"

[[bin]]
name = "typical90-b"
path = "src/b.rs"

[[bin]]
name = "typical90-c"
path = "src/c.rs"

[[bin]]
name = "typical90-d"
path = "src/d.rs"

[[bin]]
name = "typical90-e"
path = "src/e.rs"

[[bin]]
name = "typical90-f"
path = "src/f.rs"

[[bin]]
name = "typical90-w"
path = "src/w.rs"

[[bin]]
name = "typical90-y"
path = "src/y.rs"

[[bin]]
name = "typical90-ai"
path = "src/ai.rs"

[[bin]]
name = "typical90-an"
path = "src/an.rs"

[[bin]]
name = "typical90-ao"
path = "src/ao.rs"

[[bin]]
name = "typical90-as"
path = "src/as.rs"

[[bin]]
name = "typical90-aas"
path = "src/aas.rs"

[[bin]]
name = "typical90-au"
path = "src/au.rs"

[[bin]]
name = "typical90-aw"
path = "src/aw.rs"

[[bin]]
name = "typical90-bm"
path = "src/bm.rs"

[[bin]]
name = "typical90-bj"
path = "src/bj.rs"

[[bin]]
name = "typical90-bg"
path = "src/bg.rs"

[[bin]]
name = "typical90-be"
path = "src/be.rs"

[[bin]]
name = "typical90-bb"
path = "src/bb.rs"

[[bin]]
name = "typical90-ae"
path = "src/ae.rs"

[[bin]]
name = "typical90-s"
path = "src/s.rs"

[[bin]]
name = "typical90-q"
path = "src/q.rs"

[[bin]]
name = "typical90-o"
path = "src/o.rs"

[[bin]]
name = "typical90-k"
path = "src/k.rs"

[[bin]]
name = "typical90-i"
path = "src/i.rs"

[[bin]]
name = "typical90-bs"
path = "src/bs.rs"

[[bin]]
name = "typical90-bp"
path = "src/bp.rs"

[[bin]]
name = "typical90-bq"
path = "src/bq.rs"

[[bin]]
name = "typical90-ce"
path = "src/ce.rs"

[[bin]]
name = "typical90-cj"
path = "src/cj.rs"

[[bin]]
name = "typical90-ck"
path = "src/ck.rs"

[[bin]]
name = "typical90-cl"
path = "src/cl.rs"
