[package]
name = "digitalarts-rs"
version = "0.1.0"
authors = ["hiratasa <36002166+hiratasa@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.2.1"
rustc-hash = "1.1.0"
itertools = "0.9.0"
ordered-float = "1.0.2"

[[bin]]
name = "digitalarts-a"
path = "src/a.rs"

[[bin]]
name = "digitalarts-b"
path = "src/b.rs"

[[bin]]
name = "digitalarts-c"
path = "src/c.rs"

[[bin]]
name = "digitalarts-d"
path = "src/d.rs"

[[bin]]
name = "digitalarts-e"
path = "src/e.rs"

[[bin]]
name = "digitalarts-f"
path = "src/f.rs"
