[package]
name = "tdpc-rs"
version = "0.1.0"
authors = ["hiratasa <36002166+hiratasa@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.2.1"
rustc-hash = "1.1.0"
bitset-fixed = "0.1.0"
itertools = "0.9.0"
ordered-float = "1.0.2"
itertools-num = "0.1.3"
rand = { version = "0.7.3", features = ["small_rng"] }
permutohedron = "0.2.4"
proconio = "0.3.6"

[[bin]]
name = "tdpc-a"
path = "src/a.rs"

[[bin]]
name = "tdpc-b"
path = "src/b.rs"

[[bin]]
name = "tdpc-c"
path = "src/c.rs"

[[bin]]
name = "tdpc-d"
path = "src/d.rs"

[[bin]]
name = "tdpc-e"
path = "src/e.rs"

[[bin]]
name = "tdpc-f"
path = "src/f.rs"

[[bin]]
name = "tdpc-i"
path = "src/i.rs"

[[bin]]
name = "tdpc-g"
path = "src/g.rs"

[[bin]]
name = "tdpc-h"
path = "src/h.rs"

[[bin]]
name = "tdpc-j"
path = "src/j.rs"

[[bin]]
name = "tdpc-k"
path = "src/k.rs"

[[bin]]
name = "tdpc-k2"
path = "src/k2.rs"

[[bin]]
name = "tdpc-l"
path = "src/l.rs"

[[bin]]
name = "tdpc-m"
path = "src/m.rs"

[[bin]]
name = "tdpc-n"
path = "src/n.rs"

[[bin]]
name = "tdpc-o"
path = "src/o.rs"

[[bin]]
name = "tdpc-p"
path = "src/p.rs"

[[bin]]
name = "tdpc-r"
path = "src/r.rs"
